### ISSUE TITLE
Vulnerability hunting checklist

### ISSUE THREAD

**Issue by ggutoski** [axelarnetwork/tofn#153]
Need to comb through tofn code to hunt down the last few problem spots:
- [x]  eliminate panics (it's hopeless 🙁 )
- [x]  check for places where we need secure erasures of secrets in memory
- [x]  check the tofn API to make sure no leakage of secrets is allowed via various queries, "injection attacks" (put a command inside some field to trigger a malicious behavior), etc.  This item excludes #158 .
- [x] NCC audit findings (including appendix): non-Paillier #157 
- [x] NCC audit findings (including appendix): Paillier #160

**Comment by milapsheth** [comment]
Finding 005 was addressed in #173
